packages:
  - .
  - ui
  - extensions/*

onlyBuiltDependencies:
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - "@napi-rs/canvas"
  - "@tloncorp/api"
  - "@whiskeysockets/baileys"
  - authenticate-pam
  - esbuild
  - protobufjs
  - sharp
