export const browserCoreExamples = [
  "remoteclaw browser status",
  "remoteclaw browser start",
  "remoteclaw browser stop",
  "remoteclaw browser tabs",
  "remoteclaw browser open https://example.com",
  "remoteclaw browser focus abcd1234",
  "remoteclaw browser close abcd1234",
  "remoteclaw browser screenshot",
  "remoteclaw browser screenshot --full-page",
  "remoteclaw browser screenshot --ref 12",
  "remoteclaw browser snapshot",
  "remoteclaw browser snapshot --format aria --limit 200",
  "remoteclaw browser snapshot --efficient",
  "remoteclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "remoteclaw browser navigate https://example.com",
  "remoteclaw browser resize 1280 720",
  "remoteclaw browser click 12 --double",
  'remoteclaw browser type 23 "hello" --submit',
  "remoteclaw browser press Enter",
  "remoteclaw browser hover 44",
  "remoteclaw browser drag 10 11",
  "remoteclaw browser select 9 OptionA OptionB",
  "remoteclaw browser upload /tmp/remoteclaw/uploads/file.pdf",
  'remoteclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "remoteclaw browser dialog --accept",
  'remoteclaw browser wait --text "Done"',
  "remoteclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "remoteclaw browser console --level error",
  "remoteclaw browser pdf",
];
