#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${REMOTECLAW_INSTALL_E2E_IMAGE:-${CLAWDBOT_INSTALL_E2E_IMAGE:-remoteclaw-install-e2e:local}}"
INSTALL_URL="${REMOTECLAW_INSTALL_URL:-${CLAWDBOT_INSTALL_URL:-https://remoteclaw.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
REMOTECLAW_E2E_MODELS="${REMOTECLAW_E2E_MODELS:-${CLAWDBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e REMOTECLAW_INSTALL_URL="$INSTALL_URL" \
  -e REMOTECLAW_INSTALL_TAG="${REMOTECLAW_INSTALL_TAG:-${CLAWDBOT_INSTALL_TAG:-latest}}" \
  -e REMOTECLAW_E2E_MODELS="$REMOTECLAW_E2E_MODELS" \
  -e REMOTECLAW_INSTALL_E2E_PREVIOUS="${REMOTECLAW_INSTALL_E2E_PREVIOUS:-${CLAWDBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e REMOTECLAW_INSTALL_E2E_SKIP_PREVIOUS="${REMOTECLAW_INSTALL_E2E_SKIP_PREVIOUS:-${CLAWDBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
